version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "saga-pattern-example-account-balance-transfer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-10jbago8rc072"
s3_prefix = "saga-pattern-example-account-balance-transfer"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
profile = "spati-poc"
